In [1]:
class person():
    name="alice"
    age=25
a=person()

In [2]:
a

In [3]:
a.name

'alice'

In [4]:
a.age

25

In [5]:
a.name="bob"

In [6]:
a.name

'bob'

In [7]:
class person():
    name="alice"
    occ="HR"
    def info(self):
        print(f"{self.name} is a {self.occ}")
a=person()

In [8]:
a

In [9]:
a.info()

alice is a HR


In [10]:
class person():
    name="alice"
    occ="HR"
    def info(self):
        print(f"{self.name} is a {self.occ}")


In [11]:
a=person()

In [12]:
b=person()

In [13]:
b.name="BOB"
b.occ="trainer"

In [14]:
a.info()

alice is a HR


In [15]:
b.info()

BOB is a trainer


In [16]:
class person():
    name="alice"
    age=25
a=person()

In [17]:
a

In [18]:
class person():
    def __init__(self):
         print("hi")
a=person()

hi


In [19]:
class person():
    def __init__(self,name,occ):
        self.name=name
        self.occ=occ
    def info(self):
            print(f"{self.name} is a {self.occ}")
a=person("alice","hr")

In [20]:
a.info()

alice is a hr


In [21]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=list(zip(l1,l2))

In [22]:
l3

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [23]:
import time
size=10_00_000
l1=list(range(size))
l2=list(range(size))
start=time.time()
l3=[x*y for x,y in zip(l1,l2)]
end=time.time()
print(l3[0:10])
print(f"Time taken by a list is {end-start}")

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Time taken by a list is 0.22459864616394043


In [24]:
import time
import numpy as np
size=10_00_000
arr1=np.array(list(range(size)))
arr2=np.array(list(range(size)))
start=time.time()
arr3=arr1*arr2
end=time.time()
print(arr3[0:10])
print(f"Time taken by a list is {end-start}")

[ 0  1  4  9 16 25 36 49 64 81]
Time taken by a list is 0.00427699089050293


In [25]:
arr=np.array([1,2,3])

In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr=np.array([1,2,3,"hi"])
arr

array(['1', '2', '3', 'hi'], dtype='<U21')

In [29]:
import sys
list_data=list(range(1000))
arr_data=np.array(list_data)
print(f"number of memory used by list is {sys.getsizeof(list_data)} bytes")
print(f"number of memory used by array is {arr_data.nbytes} bytes")

number of memory used by list is 8056 bytes
number of memory used by array is 8000 bytes


In [30]:
arr_new_data=arr_data.astype(np.int32)
arr_new_data.nbytes

4000

# vectorization

In [31]:
list_data=[1,2,3,4]                                      
list_square=[x**2 for x in list_data]
print(list_square)                                               # simple instruction multiple data=simd
arr=np.array(list_data)                                    
arr_square=arr**2
print(arr_square)

[1, 4, 9, 16]
[ 1  4  9 16]


# dimension array

In [32]:
import numpy as np

# 1d array

In [33]:
arr=np.array([1,2,3,4,5,6])

In [34]:
arr

array([1, 2, 3, 4, 5, 6])

# 2d array

In [35]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 3d array

In [37]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [38]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

# built in method

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.full((4,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [45]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [46]:
arr=np.array([[10,20,30],[40,50,60]])

In [47]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

# properties of array

In [48]:
arr.shape

(2, 3)

In [49]:
arr.size

6

In [50]:
arr.ndim

2

In [51]:
arr.dtype

dtype('int64')

In [54]:
arr=np.array([1.1,2.2,3.3],dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [56]:
arr=np.array([1.1,2.2,3.3])
arr1=arr.astype(np.int64)
arr1

array([1, 2, 3])

In [57]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
arr.shape

(4, 3)

In [59]:
arr.size

12

In [62]:
my_arr=arr.reshape(6,2)

In [63]:
my_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [66]:
my_arr=arr.reshape(3,4)

In [67]:
my_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
my_arr=arr.reshape(12,1)

In [71]:
my_arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [72]:
my_arr=arr.reshape(1,12)

In [73]:
my_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [74]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
my_arr=arr.flatten()

In [76]:
my_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# indexing

In [77]:
arr=np.array([50,60,70,80,90,55])

In [78]:
arr[0]

np.int64(50)

In [79]:
arr[3]

np.int64(80)

In [80]:
arr[-1]

np.int64(55)

# slicing

In [81]:
arr[0:5]

array([50, 60, 70, 80, 90])

In [82]:
arr[0:5-4]

array([50])

In [83]:
arr[1:3]

array([60, 70])

In [84]:
arr[1:6]

array([60, 70, 80, 90, 55])

In [85]:
arr[0:4]

array([50, 60, 70, 80])

In [86]:
arr[:4]            #equal to[0:4]

array([50, 60, 70, 80])

In [88]:
arr[3:6]

array([80, 90, 55])

In [89]:
arr[3:]             #equal to [3:4]

array([80, 90, 55])

In [92]:
my_list=[1,2,3,4,5,6]
print(my_list)
new_list=my_list[0:4]                        # for list
print(new_list)
new_list[0]=100
print(new_list)
print(my_list)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4]
[100, 2, 3, 4]
[1, 2, 3, 4, 5, 6]


In [97]:
my_array=np.array([1,2,3,4,5,6])
print(my_array)
new_array=my_array[0:4].copy()
print(new_array)
new_array[0]=100
print(new_array)
print(my_array)

[1 2 3 4 5 6]
[1 2 3 4]
[100   2   3   4]
[1 2 3 4 5 6]


# multidimensional array mathematical operation

In [2]:
import numpy as np

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
arr.shape

(4, 3)

In [7]:
arr[0][1]

np.int64(2)

In [8]:
arr[2,1]

np.int64(8)

In [9]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [10]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
arr[1:4,1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [12]:
arr[4:6,4:10]

array([], shape=(0, 0), dtype=int64)

# 3D array

In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [18]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr[0,1,2]

np.int64(6)

In [20]:
arr[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

# built in mathematical functions

In [21]:
arr=np.array([1,2,3,4,5])

In [22]:
np.mean(arr)

np.float64(3.0)

In [24]:
np.min(arr)

np.int64(1)

In [23]:
np.max(arr)

np.int64(5)

In [25]:
np.std(arr)

np.float64(1.4142135623730951)

In [26]:
np.var(arr)

np.float64(2.0)

In [27]:
np.sum(arr)

np.int64(15)

In [28]:
np.prod(arr)

np.int64(120)

In [30]:
np.median(arr)

np.float64(3.0)

In [32]:
np.percentile(arr,50)

np.float64(3.0)

In [33]:
np.argmin(arr)

np.int64(0)

In [34]:
np.argmax(arr)

np.int64(4)

In [35]:
np.corrcoef(arr)                                  #correlation coefficient

np.float64(1.0)

In [36]:
x=[1,2,3]
y=[2,4,6]
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [37]:
x=[1,2,3]
y=[8,6,4]
np.corrcoef(x,y)

array([[ 1., -1.],
       [-1.,  1.]])

In [38]:
x=[1,2,3]
y=[5,1,8]
np.corrcoef(x,y)

array([[1.       , 0.4271211],
       [0.4271211, 1.       ]])

In [39]:
arr1=np.array([1,2,3,4,5,2,4,6,4,2])
np.unique(arr)

array([1, 2, 3, 4, 5])

In [40]:
np.diff(arr)                                  # nth diff

array([1, 1, 1, 1])

In [42]:
np.cumsum(arr)                             # cumulative sum

array([ 1,  3,  6, 10, 15])

In [44]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [46]:
np.log(1)

np.float64(0.0)

In [47]:
np.exp(1)

np.float64(2.718281828459045)